package com.infosys.inventory.util;

import com.infosys.inventory.dao.ProductDao;
import com.infosys.inventory.model.Product;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GenerateCSV {

    private static final String REPORT_DIR = "reports/";

    public void reportCSV(String filePath){
        ProductDao dao = new ProductDao();
        ArrayList<Product> productArrayList = dao.getAllProducts();
        try(PrintWriter writer = new PrintWriter(new File(filePath))){
            writer.println("ProductId,ProductName,ProductQuantity,ProductPrice,ProductCategory");
            for(Product pro:productArrayList){
                writer.println(pro.getProductId()+","+pro.getProductName()+","+pro.getQuantity()+","+ pro.getPrice()+","+pro.getCategory());
            }
            System.out.println("File is created at : " + filePath);
        }catch (FileNotFoundException e){
            System.out.println("Error cause while creating csv file : "+ e.getMessage());
        }

    }

    public static String generateProductsReport(List<Product> products, String generatedBy) {
        try {
            File dir = new File(REPORT_DIR);
            if (!dir.exists()) dir.mkdirs();

            String fileName = REPORT_DIR + "inventory_report_" +
                    new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date()) + ".csv";

            try (PrintWriter out = new PrintWriter(new FileWriter(fileName))) {
                out.println("=== Inventory Report ===");
                out.println("Generated By: " + generatedBy);
                out.println("Generated On: " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()));
                out.println("ID,Name,Quantity,Price,Category");

                if (products != null && !products.isEmpty()) {
                    for (Product p : products) {
                        out.println(p.getProductId() + "," +
                                p.getProductName() + "," +
                                p.getQuantity() + "," +
                                p.getPrice() + "," +
                                p.getCategory());
                    }
                } else {
                    out.println("⚠️ No products available.");
                }

                out.println("----------------------------------------");
                out.println("Total Products: " + (products != null ? products.size() : 0));
            }

            System.out.println("✅ Report saved successfully: " + fileName);
            return fileName;

        } catch (Exception e) {
            System.out.println("❌ Error writing report: " + e.getMessage());
            return null;
        }
    }
}
